export const books = [
  // {
  //   id: ,
  //   name: '',
  //   author: '',
  //   bookRating: '',
  //   cover: '',
  //   GR: '',
  // },
  {
    id: 5,
    name: `A Nobleman's Guide to Seducing a Scoundrel`,
    author: 'K.J. Charles',
    bookRating: '5',
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1677601132i/75505273.jpg',
    GR: 'https://www.goodreads.com/book/show/75505273-a-nobleman-s-guide-to-seducing-a-scoundrel',
    SG: 'https://app.thestorygraph.com/books/712bc0ff-9cd1-4f85-8e46-116e30dbc26f',
    textB: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas odio, vitae scelerisque enim ligula venenatis dolor. Maecenas nisl est, ultrices nec congue eget, auctor vitae massa. Fusce luctus vestibulum augue ut aliquet. Mauris ante ligula, facilisis sed ornare eu, lobortis in odio.",
    textE: `The second book of the series! Now one of the side characters from the first installment is the main protagonist in this story. Again, incredible writing, plot twists and mystery that keeps you glued to the book until the "Acknowledgment" page, great side characters, character development - it has everything!!`,
    tropes: 'historical fiction, mystery, friends to lovers, forced proximity',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://www.goodreads.com/notes/75505273-a-nobleman-s-guide-to-seducing-a-scoundrel/124881434-lena?ref=abp',
  },
  {
    id: 4,
    name: 'The Secret Lives of Country Gentlemen',
    author: 'K.J. Charles',
    bookRating: '5',
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1663091297i/61215948.jpg',
    GR: 'https://www.goodreads.com/book/show/61215948-the-secret-lives-of-country-gentlemen',
    SG: 'https://app.thestorygraph.com/books/bae89175-2576-4f31-9e78-9f611cfb1cff',
    textB: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas odio, vitae scelerisque enim ligula venenatis dolor. Maecenas nisl est, ultrices nec congue eget, auctor vitae massa. Fusce luctus vestibulum augue ut aliquet. Mauris ante ligula, facilisis sed ornare eu, lobortis in odio.",
    textE: `I suggested this book to @bensmom33 when I was going through my pile of "Blind date with a book" books, and I vividly remember selecting this book at the store and had NO idea it will have such a hold on me!! Captivating writing, compelling story, great main characters that grow throughout the story, incredible side characters and a good ol' mystery! Can't believe how much I loved this book, to the point that we both wanted to read the next book in the series!!`,
    tropes: 'historical fiction, mystery, hooking-up-strangers to enemies to lovers, misunderstandings',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://www.goodreads.com/notes/61215948-the-secret-lives-of-country-gentlemen/124881434-lena?ref=abp',
  },
  {
    id: 3,
    name: 'Boyfriend Material',
    author: 'Alexis Hall',
    bookRating: '0.5',
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1578640390i/48994908.jpg',
    GR: 'https://www.goodreads.com/book/show/48994908-boyfriend-material',
    SG: 'https://app.thestorygraph.com/books/b47dcd5f-827f-44f5-bda6-8e49af6f9c6e',
    textB: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas odio, vitae scelerisque enim ligula venenatis dolor. Maecenas nisl est, ultrices nec congue eget, auctor vitae massa. Fusce luctus vestibulum augue ut aliquet. Mauris ante ligula, facilisis sed ornare eu, lobortis in odio.",
    textE: "Welp, a good example of so many people ALSO raving about this one and this was not even close to being a good read. I think we hate-read it in 2 or 3 days just to get over it. Blergh!! The main character is so annoying and whiny that I wanted to throw my kindle every three pages; the side characters might as well not be there (except for the love interest's friends), and honestly the only decent character we get is main protagonist's love interest. I wanted to stage an intervention and rescue him from the main cuckoo guy. ",
    tropes: 'fake dating, modern setting',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://www.goodreads.com/notes/48994908-boyfriend-material/124881434-lena?ref=abp',
  },
  {
    id: 2,
    name: 'You Should Be So Lucky',
    author: 'Cat Sebastian',
    bookRating: '5',
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1706543774i/196774809.jpg',
    GR: 'https://www.goodreads.com/book/show/196774809-you-should-be-so-lucky',
    SG: 'https://app.thestorygraph.com/books/20564f3e-5358-412a-a9ec-b18ea171bf11',
    textB: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas odio, vitae scelerisque enim ligula venenatis dolor. Maecenas nisl est, ultrices nec congue eget, auctor vitae massa. Fusce luctus vestibulum augue ut aliquet. Mauris ante ligula, facilisis sed ornare eu, lobortis in odio.",
    textE: `The second book of the series! One of the side characters from the first installment is the main protagonist in this story. Loved character development, a different set of circumstances, not just a carbon copy of the first book with different names. Our favorite characters from the first book make an appearance here, and it doesn't feel gratuitous, for which I'm grateful.`,
    tropes: 'historical fiction, strangers to reluctant friends to lovers, forced proximity',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://www.goodreads.com/notes/196774809-you-should-be-so-lucky/124881434-lena?ref=abp',
  },
  {
    id: 1,
    name: 'We Could Be So Good',
    author: 'Cat Sebastian',
    bookRating: '5',
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1674685755i/62365905.jpg',
    GR: 'https://www.goodreads.com/book/show/62365905-we-could-be-so-good',
    SG: 'https://app.thestorygraph.com/books/d6d54203-0ada-4b36-9183-580c244425da',
    textB: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas odio, vitae scelerisque enim ligula venenatis dolor. Maecenas nisl est, ultrices nec congue eget, auctor vitae massa. Fusce luctus vestibulum augue ut aliquet. Mauris ante ligula, facilisis sed ornare eu, lobortis in odio.",
    textE: "I don't like reading historical novels but SO many people were raving about this series that I finally decided to give it a chance. And thank God I did!!! Didn't regret it for one second. The writing is exquisite, the main characters are very real and well-written, the side characters are not just placeholders but add to the story quite a bit. A very memorable book that I will be recommending to everyone!",
    tropes: 'secret workplace romance, strangers to friends to lovers, historical fiction',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://drive.google.com/file/d/1g8VIdYEuRq1KMHUdcf-ZPUWetBEfp8Ha/view?usp=sharing',
  }
];