export const books = [
  {
    id: 9,
    name: `The Long Game`,
    author: 'Rachel Reid',
    bookRating: '5',
    spiceRating: 100,
    cover: 'https://images.squarespace-cdn.com/content/v1/5a218847cd39c361e7a82ae9/1733361543080-2B35183LXCISB2BA3UD6/9781335534644.jpg?format=750w',
    GR: 'https://www.goodreads.com/book/show/220966428-the-long-game',
    SG: 'https://app.thestorygraph.com/books/440446f5-b3ed-45a2-b37a-9e3924e7beae',
    textB: "Vivamus in mauris odio. Donec non laoreet quam, at porta ex. Mauris pharetra lectus sit amet vulputate egestas. Quisque elementum fringilla lectus, vitae blandit magna consectetur vel. Nunc non rutrum magna. Fusce quis lobortis ante. Nam a suscipit nisl, ac mattis felis. Nullam tortor tellus, semper quis fermentum eu, elementum sit amet elit.",
    textE: ``,
    tropes: 'contemporary hockey romance, secret relationship',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://www.goodreads.com/notes/220966494-heated-rivalry/124881434-lena',
  },
  {
    id: 8,
    name: `Heated Rivalry`,
    author: 'Rachel Reid',
    bookRating: '5',
    spiceRating: 100,
    cover: 'https://images.squarespace-cdn.com/content/v1/5a218847cd39c361e7a82ae9/1733361541915-858D7NBE77EL8HJG8FWG/9781335534637.jpg?format=750w',
    GR: 'https://www.goodreads.com/book/show/220966494-heated-rivalry',
    SG: 'https://app.thestorygraph.com/books/c3349f20-b3a0-4894-9d79-0ffa7600c629',
    textB: "Pellentesque magna neque, tincidunt eget ipsum et, pellentesque eleifend turpis. Fusce hendrerit congue est, at varius tortor tincidunt vitae. Mauris elementum urna eu odio rutrum, quis suscipit elit ultricies. Suspendisse ligula enim, gravida ac nibh nec, scelerisque congue ex.",
    textE: ``,
    tropes: 'contemporary hockey romance, forbidden relationship, enemies to lovers',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://www.goodreads.com/notes/220966494-heated-rivalry/124881434-lena',
  },
  {
    id: 7,
    name: `The Charm Offensive`,
    author: 'Alison Cochrun',
    bookRating: '4.25',
    spiceRating: 40,
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1726978796i/56997152.jpg',
    GR: 'https://www.goodreads.com/book/show/56997152-the-charm-offensive',
    SG: 'https://app.thestorygraph.com/books/0d53fbac-ab71-4de5-b6a8-8d3c442b97df',
    textB: "Donec et mi sagittis, porttitor massa sed, sollicitudin felis. Aenean euismod nibh non sagittis ultricies. Phasellus sit amet mauris nec erat elementum mattis sit amet nec libero. Aliquam erat volutpat. Ut bibendum mattis sagittis. In vitae commodo dolor, vel scelerisque dui.",
    textE: ``,
    tropes: 'contemporary romance, reality show',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://www.goodreads.com/notes/56997152-the-charm-offensive/124881434-lena',
  },
  {
    id: 6,
    name: `Solomon's Crown`,
    author: 'Natasha Siegel',
    bookRating: '4.25',
    spiceRating: 20,
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1674296131i/74823499.jpg',
    GR: 'https://www.goodreads.com/book/show/74823499-solomon-s-crown',
    SG: 'https://app.thestorygraph.com/books/a2041479-3797-4452-b995-e3281155c1a8',
    textB: "Integer tincidunt, ipsum et dignissim porttitor, tellus neque vulputate turpis, auctor posuere magna justo ut orci. In sollicitudin magna id sem pretium, tristique cursus leo efficitur. Suspendisse accumsan eget libero vestibulum rhoncus. Vestibulum vitae convallis ipsum. Integer malesuada neque urna, eu pulvinar tortor porta non.",
    textE: ``,
    tropes: 'historical fiction, friends to rivals to lovers',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://www.goodreads.com/notes/74823499-solomon-s-crown/124881434-lena',
  },
  {
    id: 5,
    name: `A Nobleman's Guide to Seducing a Scoundrel`,
    author: 'K.J. Charles',
    bookRating: '4',    
    spiceRating: 35,
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1677601132i/75505273.jpg',
    GR: 'https://www.goodreads.com/book/show/75505273-a-nobleman-s-guide-to-seducing-a-scoundrel',
    SG: 'https://app.thestorygraph.com/books/712bc0ff-9cd1-4f85-8e46-116e30dbc26f',
    textB: "Sed venenatis urna eget nibh pretium, id ullamcorper magna tempus. Suspendisse rhoncus ultrices posuere. Donec nec vulputate purus. Phasellus pretium luctus vulputate. Duis faucibus, purus vitae rhoncus ornare, velit erat suscipit nisl, ut egestas neque nisi sit amet dui. Sed vestibulum nec elit at rhoncus. Nulla facilisi.",
    textE: `The second book of the series! Now one of the side characters from the first installment is the main protagonist in this story. Again, incredible writing, plot twists and mystery that keeps you glued to the book until the "Acknowledgment" page, great side characters, character development - it has everything!!`,
    tropes: 'historical fiction, mystery, friends to lovers, forced proximity',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://www.goodreads.com/notes/75505273-a-nobleman-s-guide-to-seducing-a-scoundrel/124881434-lena',
  },
  {
    id: 4,
    name: 'The Secret Lives of Country Gentlemen',
    author: 'K.J. Charles',
    bookRating: '4',
    spiceRating: 35,
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1663091297i/61215948.jpg',
    GR: 'https://www.goodreads.com/book/show/61215948-the-secret-lives-of-country-gentlemen',
    SG: 'https://app.thestorygraph.com/books/bae89175-2576-4f31-9e78-9f611cfb1cff',
    textB: "Phasellus suscipit interdum volutpat. Nullam rutrum fringilla purus non luctus. Proin dignissim lectus eu lorem volutpat, blandit porttitor mi pretium. Duis fringilla at diam at auctor. Donec sed ante at eros euismod feugiat ac nec odio.",
    textE: `I suggested this book to @bensmom33 when I was going through my pile of "Blind date with a book" books, and I vividly remember selecting this book at the store and had NO idea it will have such a hold on me!! Captivating writing, compelling story, great main characters that grow throughout the story, incredible side characters and a good ol' mystery! Can't believe how much I loved this book, to the point that we both wanted to read the next book in the series!!`,
    tropes: 'historical fiction, mystery, hooking-up-strangers to enemies to lovers, misunderstandings',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://www.goodreads.com/notes/61215948-the-secret-lives-of-country-gentlemen/124881434-lena',
  },
  {
    id: 3,
    name: 'Boyfriend Material',
    author: 'Alexis Hall',
    bookRating: '0.25',
    spiceRating: 5,
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1578640390i/48994908.jpg',
    GR: 'https://www.goodreads.com/book/show/48994908-boyfriend-material',
    SG: 'https://app.thestorygraph.com/books/b47dcd5f-827f-44f5-bda6-8e49af6f9c6e',
    textB: "A poor man's Bridget Jones' Diary that sacrifices any character development on the altar of look at me I'm funny. If the author's goal was to make me hate everyone in the book, well then mission accomplished.",
    textE: "Welp, a good example of so many people ALSO raving about this one and this was not even close to being a good read. I think we hate-read it in 2 or 3 days just to get over it. Blergh!! The main character is so annoying and whiny that I wanted to throw my kindle every three pages; the side characters might as well not be there (except for the love interest's friends), and honestly the only decent character we get is main protagonist's love interest. I wanted to stage an intervention and rescue him from the main cuckoo guy. ",
    tropes: 'fake dating, modern setting',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://www.goodreads.com/notes/48994908-boyfriend-material/124881434-lena',
  },
  {
    id: 2,
    name: 'You Should Be So Lucky',
    author: 'Cat Sebastian',
    bookRating: '5',
    spiceRating: 27.5,
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1706543774i/196774809.jpg',
    GR: 'https://www.goodreads.com/book/show/196774809-you-should-be-so-lucky',
    SG: 'https://app.thestorygraph.com/books/20564f3e-5358-412a-a9ec-b18ea171bf11',
    textB: "Vivamus eleifend risus quis neque hendrerit sollicitudin. Pellentesque interdum volutpat viverra. Donec sed cursus augue. Nulla ornare porttitor tellus, at blandit nulla interdum quis. Vestibulum dignissim, mi id consequat commodo, ipsum risus venenatis massa, vitae placerat ante libero eu orci. Etiam elementum lacus ac augue placerat semper.",
    textE: `The second book of the series! One of the side characters from the first installment is the main protagonist in this story. Loved character development, a different set of circumstances, not just a carbon copy of the first book with different names. Our favorite characters from the first book make an appearance here, and it doesn't feel gratuitous, for which I'm grateful.`,
    tropes: 'historical fiction, strangers to reluctant friends to lovers, forced proximity',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://www.goodreads.com/notes/196774809-you-should-be-so-lucky/124881434-lena',
  },
  {
    id: 1,
    name: 'We Could Be So Good',
    author: 'Cat Sebastian',
    bookRating: '5',
    spiceRating: 30.5,
    cover: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1674685755i/62365905.jpg',
    GR: 'https://www.goodreads.com/book/show/62365905-we-could-be-so-good',
    SG: 'https://app.thestorygraph.com/books/d6d54203-0ada-4b36-9183-580c244425da',
    textB: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas odio, vitae scelerisque enim ligula venenatis dolor. Maecenas nisl est, ultrices nec congue eget, auctor vitae massa. Fusce luctus vestibulum augue ut aliquet. Mauris ante ligula, facilisis sed ornare eu, lobortis in odio.",
    textE: "I don't like reading historical novels but SO many people were raving about this series that I finally decided to give it a chance. And thank God I did!!! Didn't regret it for one second. The writing is exquisite, the main characters are very real and well-written, the side characters are not just placeholders but add to the story quite a bit. A very memorable book that I will be recommending to everyone!",
    tropes: 'secret workplace romance, strangers to friends to lovers, historical fiction',
    addOns: 'GRs, fanart, etc',
    highlightsE: 'https://www.goodreads.com/notes/60630848-we-could-be-so-good/124881434-lena',
  }
];